# Generated by Django 5.2.15 on 2026-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('image_url', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('color_r', models.PositiveSmallIntegerField(null=True)),
                ('color_g', models.PositiveSmallIntegerField(null=True)),
                ('color_b', models.PositiveSmallIntegerField(null=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'name'],
            },
        ),
    ]
