# Generated by Django 5.2.15 on 2026-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='fiber',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yarn',
            name='skein_weight_grams',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='yarn_type',
            field=models.CharField(blank=True, choices=[('lace', 'Lace'), ('fingering', 'Fingering'), ('sport', 'Sport'), ('dk', 'DK'), ('worsted', 'Worsted'), ('aran', 'Aran'), ('bulky', 'Bulky'), ('super_bulky', 'Super Bulky'), ('jumbo', 'Jumbo')], default='', max_length=20),
        ),
    ]
