# Generated by Django 5.2.15 on 2026-06-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0002_yarn_fiber_yarn_skein_weight_grams_yarn_yarn_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='skein_weight_grams',
        ),
    ]
