# Generated by Django 5.2.15 on 2026-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0003_drop_skein_weight_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='yarn_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
