# Generated by Django 5.2.15 on 2026-06-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0004_expand_yarn_type_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='yarns.yarn')),
            ],
            options={
                'unique_together': {('user', 'yarn')},
            },
        ),
    ]
