# Generated by Django 5.2.15 on 2026-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0005_add_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
