# Generated by Django 5.2.15 on 2026-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0006_alter_yarn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='fiber',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='source',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='yarn_type',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
